# 动态规划

# 1. 钢条切割

In [17]:
import sys

# 朴素递归算法
def CutRod(p, n):
    if(0 == n):
        return 0
    q = 0
    for i in range(0, n):
        q = max(q, p[i] + CutRod(p, n-1-i))
    return q

# 带备忘的自顶向下法(top-down with memoization)
def MemoizedCutRod(p, n):
    r = [0] * n
    return MemoizedCutRodAux(p, n, r)
        
def MemoizedCutRodAux(p, n, r):
    if(0 == n):
        return 0
    if(r[n-1] > 0):
        return r[n-1]
    q = 0
    if(n > 0):
        for i in range(n):
            q = max(q, p[i] + MemoizedCutRodAux(p, n-1-i, r))
    r[n-1] = q
    return q

# 自底向上法
def ButtonUpCutRodAux(p, n):
    #r[k] 用于表示钢管长度为k时，最大能组合成的价格
    r = [0] * (n+1)
    for j in range(1, n+1):
        q = 0
        for i in range(1, j+1):
            q = max(q, p[i-1]+r[j-i])
        r[j] = q
    return r[n]

p = [1,5,8,9]  #p[i] 指钢管长度为i+1时的价格
maxval1 = CutRod(p, 4)
maxval2 = MemoizedCutRod(p, 4)
maxval3 = ButtonUpCutRodAux(p, 4)
print((maxval2, maxval3))

(10, 10)


# 2. 最长公共子序列

In [10]:
import numpy as np

class LCS:
    def __init__(self, str1, str2):
        self.str1 = str1
        self.str2 = str2
        self.matrix = np.zeros((len(str1)+1, len(str2)+1), dtype=np.int32)
    
    def LCSLength(self):
        for i in range(1, len(self.str1)+1):
            for j in range(1, len(self.str2)+1):
                if(self.str1[i-1] == self.str2[j-1]):
                    self.matrix[i][j] = self.matrix[i-1][j-1] + 1
                elif(self.matrix[i-1][j] >= self.matrix[i][j-1]):
                    self.matrix[i][j] = self.matrix[i-1][j]
                else:
                    self.matrix[i][j] = self.matrix[i][j-1]
    
    def PrintLCS(self, i, j):
        if(0==i or 0 == j):
            return
        if(self.matrix[i][j] == self.matrix[i-1][j]):
            self.PrintLCS(i-1, j)
        elif(self.matrix[i][j] == self.matrix[i][j-1]):
            self.PrintLCS(i, j-1)
        else:
            self.PrintLCS(i-1, j-1)
            print(self.str1[i-1])

if __name__=='__main__':
    str1 = ['A','B','C','B','D','A','B']
    str2 = ['B','D','C','A','B','A']
    test_lcs = LCS(str1, str2)
    test_lcs.LCSLength()
    print(test_lcs.matrix)
    test_lcs.PrintLCS(len(str1), len(str2))

                
            
    

[[0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1]
 [0 1 1 1 1 2 2]
 [0 1 1 2 2 2 2]
 [0 1 1 2 2 3 3]
 [0 1 2 2 2 3 3]
 [0 1 2 2 3 3 4]
 [0 1 2 2 3 4 4]]
B
C
B
A
